### ISSUE TITLE
Icon shadow box stretching for cards with long names

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/smr-frontend#10]
Problematic examples:

![image](https://user-images.githubusercontent.com/25965766/129989598-9a67b792-0197-4e00-9c89-630974309680.png)

![image](https://user-images.githubusercontent.com/25965766/129989625-de3b436b-ccd9-41ce-8778-bd6ec50d4d80.png)

Looks fine examples:

![image](https://user-images.githubusercontent.com/25965766/129989651-7de73599-b3b9-4cc1-a502-bc813b8ef76c.png)

![image](https://user-images.githubusercontent.com/25965766/129989677-c039975c-396e-42f5-815f-bfbfa867b599.png)

**Comment by Vilsol** [comment]
Superseded by #11
