### ISSUE TITLE
Redesign mod/guide cards

### ISSUE THREAD

**Issue by Vilsol** [satisfactorymodding/smr-frontend#11]
Current cards defeat the purpose of short descriptions: an always visible piece of text. Also the fact that they slide out is unexpected and obscure other mods in the process.

**Comment by BaineGames** [comment]
Guide with no image that is currently posted is not loading a default image and is instead showing a broken image link as well.

**Comment by Vilsol** [comment]
Obsolete issue due to design rewrite.
