### ISSUE TITLE
Incorrect alignment for small tool icons

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/smr-frontend#122]
https://ficsit.dev/tools

![Image](https://github.com/satisfactorymodding/smr-frontend/assets/25965766/7bc6f9a6-e295-455f-8788-4e56021076bb)

**Comment by xXdrewbaccaXx** [comment]
Odd, the grid is set to justify center, but the card-image-counter is set to 200x90px. 
I assume that oddness is a factory. 
Could there not be a min-width max-width auto height set of properties used to fix this?

![Image](https://github.com/satisfactorymodding/smr-frontend/assets/6498504/928fe906-3539-4c48-aa90-c6ec4ffc9363)
