### ISSUE TITLE
Scroll issue - mobile

### ISSUE THREAD

**Issue by xXdrewbaccaXx** [satisfactorymodding/smr-frontend#129]
Incomplete page view when scrolling to bottom.

https://github.com/satisfactorymodding/smr-frontend/assets/6498504/9157813d-8941-4188-87b7-41fd4b5275a4

**Comment by Vilsol** [comment]
Is this still present on ficsit.dev?

**Comment by xXdrewbaccaXx** [comment]
@Vilsol just checked and no.
 I didnt see an open issue for it though, hence posting.

**Comment by Vilsol** [comment]
If it's not an issue on staging, I am closing this issue, as it doesn't apply anymore.
