### ISSUE TITLE
Poor user feedback on "search query too short"

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/smr-frontend#163]
Example: https://ficsit.app/mods?p=0&q=vr

Should have some kind of user facing error message, especially when typing a query into the box (maybe a tooltip that appears after X seconds of not typing with too short of a query?)

**Comment by SignpostMarv** [comment]
from direct link:
![image](https://github.com/satisfactorymodding/smr-frontend/assets/304403/a252d3b1-0f42-4485-931d-2862cdd56041)

from manual search (zero error feedback):
![image](https://github.com/satisfactorymodding/smr-frontend/assets/304403/6784bad9-b42e-496d-a754-c84add4a6e28)

**Comment by QuantumPickleJar** [comment]
- Only seems to trigger from the [URL provided](https://ficsit.app/mods?p=0&q=vr)

**Comment by SignpostMarv** [comment]
> * Only seems to trigger from the [URL provided](https://ficsit.app/mods?p=0&q=vr)
> * reproducing manually does _not_ cause the described behavior

* It would trigger for any sufficiently short search term, "vr" just happens to be a one common enough to actually be used
* people send people links

**Comment by budak7273** [comment]
Any too-short url (ex. <https://ficsit.app/mods?p=0&q=ab> or <https://ficsit.app/mods?p=0&q=xy>causes the GraphQL error. Trying to search from the box with <3 characters silently does nothing

**Comment by budak7273** [comment]
Fixed in #186
