### ISSUE TITLE
Mod dependency section should indicate "optional" status

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/smr-frontend#168]
https://ficsit.app/mod/DigbyTool

![Image](https://github.com/satisfactorymodding/smr-frontend/assets/25965766/97a6eb97-545d-4ac4-b5c3-74df671482f9)

![Image](https://github.com/satisfactorymodding/smr-frontend/assets/25965766/5cd31a22-8af4-4315-a78f-5a98ecaf1956)

**Comment by porisius** [comment]
Poking @Vilsol and @budak7273 
https://github.com/satisfactorymodding/smr-frontend/pull/169
https://github.com/satisfactorymodding/smr-api/pull/51
