### ISSUE TITLE
HTTP 500: New Version of Existing Mod

### ISSUE THREAD

**Issue by porisius** [satisfactorymodding/smr-frontend#30]
![image](https://user-images.githubusercontent.com/47161774/145156831-9f949ebe-8286-4243-930b-bcb922824140.png)

I was attempting to upload a new version of Disc-IT, and I got a 500 error. Screenshot attached.

500
Failed to fetch dynamically imported module: https://next.ficsit.app/_app/pages/mod/_modId_/new-version.svelte-c7ec63c2.js
TypeError: Failed to fetch dynamically imported module: https://next.ficsit.app/_app/pages/mod/_modId_/new-version.svelte-c7ec63c2.js

**Comment by Vilsol** [comment]
Should be fixed.
