### ISSUE TITLE
[Feature Request] Tags for mods and search for them

### ISSUE THREAD

**Issue by Zeratoxx** [satisfactorymodding/smr-frontend#32]
I would love tags for the listed mods. My initial idea was to especially tag those mods that are safe to use because they dont add new assets to the safefile / spoils the safefile (for example SMART, it just changes the ingame behavior using the vanilla functions and assets).
That means that you could search for mods that solely change the ingame behavior for QoL but keeps the safefiles clean.

**Comment by Feyko** [comment]
Tags are actually ready to be deployed on the backend already! I just need to implement the GUI for them. You can hopefully expect to see them in a week or so

**Comment by Zeratoxx** [comment]
Oh. That is fortunate xD

**Comment by budak7273** [comment]
Oops we forgot to close this when it launched
