### ISSUE TITLE
Latest version download arrow should download via the manager

### ISSUE THREAD

**Issue by Them8** [satisfactorymodding/smr-frontend#59]
if you don't support manual installation or downloading from the site then putting it in the modloader then you really need to put install button on the webbpages for the mods themselvs not just out in the search and in the version page as the only button in that page is the little download one.
![Button](https://user-images.githubusercontent.com/45337294/192274873-20217256-1a79-4892-867e-11e78318e44e.png)
the one shown here. it should go to download via the modloader. right now it downloads a .smod

**Comment by budak7273** [comment]
It now installs via SMM, and has a text element, but the text should be changed to "Install" and not "Download" to reflect that 
![image](https://github.com/satisfactorymodding/smr-frontend/assets/25965766/1fdb805e-0fe0-48c7-bcce-2ab7372662c3)
