### ISSUE TITLE
[Feature Request] User-facing mod dependency list

### ISSUE THREAD

**Issue by TacticalMook** [satisfactorymodding/smr-frontend#67]
A common feature in other mod repositories is a hyperlinked list of mod dependencies that the currently-viewed mod requires. Mod libraries, for example. I like and use this feature.

Another good, but less common feature is a list of mods the author has expressly flagged as incompatible or compatible with their own.

I have also wanted go the opposite direction: View mods which depend on this one, and view mods which are expressly compatible or incompatible with this one. However, I have not actually seen any mod repositories implement such a feature.

**Comment by porisius** [comment]
Up to the team to decide if you implement, but I mocked up something... along with the Multi-Target display...
![image](https://github.com/satisfactorymodding/smr-frontend/assets/47161774/cd7d2f4b-ffc7-4a1d-8623-a68ebebbf79d)

**Comment by budak7273** [comment]
Current state: 
![image](https://github.com/satisfactorymodding/smr-frontend/assets/25965766/cd323167-d608-4f96-b65f-eb64b681b47e)


However, clicking the mod text doesn't properly redirect you. Example: Click `PowerSuit` on https://ficsit.dev/mod/ArmorModules

I think @mircearoata knows how to fix this

**Comment by porisius** [comment]
ficsit.dev doesn't have a Powersuit mod in it, or at least I didn't see it. I am not sure if that is having an effect or not.

**Comment by budak7273** [comment]
@porisius it does, otherwise I wouldn't have been able to upload the mod. See <https://ficsit.dev/mod/PowerSuit>
