### ISSUE TITLE
Fix doggo easter egg typo

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/smr-frontend#77]
Doggo easter egg tooltip suggests clicking to pat, but pressing and holding pats the doggo

**Comment by AstroFloof** [comment]
>:|

**Comment by budak7273** [comment]
https://github.com/satisfactorymodding/smr-frontend/blob/ab9b27c5b727f796b1ab7cc86cd23369c9656cd3/src/lib/components/general/Doggo.svelte#L62
