### ISSUE TITLE
Test/Dev Site: Updating Compatibility removes Tags

### ISSUE THREAD

**Issue by porisius** [satisfactorymodding/smr-frontend#84]
Steps to replicate:

1) Add tags to a mod
2) Verify tags saved
3) Modify compatibility & Save
4) Check for tags again

Not sure how/where/why this one is happening.

**Comment by budak7273** [comment]
https://discord.com/channels/555424930502541343/830842478956642354/1193088303038218331

**Comment by Vilsol** [comment]
Fixed
