### ISSUE TITLE
No Auto-Close Navbar on Mobile

### ISSUE THREAD

**Issue by xXdrewbaccaXx** [satisfactorymodding/smr-frontend#93]
Navbar doesn't auto close when selecting a menu option on mobile.
Link:  https://discord.com/channels/555424930502541343/1036634533077979146/1125232859326713856

**Comment by xXdrewbaccaXx** [comment]
https://github.com/satisfactorymodding/smr-frontend/pull/128

Fix for `top` and `bottom` lists pushed.

Fix not yet implemented for auto close on click for user profile and other non list items. Couldn't figure out where the edit needed to be.




New issue with mobile; spacing is absolutely borked. 

![Screenshot_20231106_165618_Chrome.jpg](https://github.com/satisfactorymodding/smr-frontend/assets/6498504/e7e2e2de-b0eb-4ee1-9bae-59908285c661)

**Comment by xXdrewbaccaXx** [comment]
Sidebar bug fixes in PR. Waiting for review/merge.

Giant sidebar is a separate issue.

**Comment by budak7273** [comment]
(Reopened because Bun Skeleton changes how the fix needs to be implemented)

**Comment by xXdrewbaccaXx** [comment]
Can we mark this as closed now? I think the issue is resolved because of all the changes?

**Comment by budak7273** [comment]
Confirmed that it auto closes on latest ficsit.app
